# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Data < Formula
  desc ""
  homepage "https://github.com/thientran2020/data"
  version "1.0.5"

  on_macos do
    url "https://github.com/thientran2020/data/releases/download/v1.0.5/data_1.0.5_darwin_all.tar.gz"
    sha256 "b50a9acdff23ad5ad0133f3dcad179e1271ac05e575658457ff70b9b34bbab5d"

    def install
      bin.install "data"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thientran2020/data/releases/download/v1.0.5/data_1.0.5_linux_arm64.tar.gz"
      sha256 "0795fa50e09872a05eb6e192af7a85e7f5de1f961712619cca190a135fcd58ef"

      def install
        bin.install "data"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thientran2020/data/releases/download/v1.0.5/data_1.0.5_linux_amd64.tar.gz"
      sha256 "74b5dbb161f66b98889687253545943ac6fbf5f8c8627a8b731ea312872985a1"

      def install
        bin.install "data"
      end
    end
  end
end
