# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinancialCli < Formula
  desc ""
  homepage "https://github.com/thientran2020/financial-cli"
  version "1.0.0"

  on_macos do
    url "https://github.com/thientran2020/financial-cli/releases/download/v1.0.0/financial-cli_1.0.0_darwin_all.tar.gz"
    sha256 "675b692ab172543e6cb251d8e1b01a038079922e5f38d72b153ac97f51707b9e"

    def install
      bin.install "financial-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thientran2020/financial-cli/releases/download/v1.0.0/financial-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "54d2779333683e6bafbd232526cc0f91deb1fee8f40176015cdafff8acbddc55"

      def install
        bin.install "data"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thientran2020/financial-cli/releases/download/v1.0.0/financial-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "99b1c79562e089a6e007086f9b58872b8c7703ac63268b77e11c67a523c12915"

      def install
        bin.install "data"
      end
    end
  end
end
