# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class N400 < Formula
  desc ""
  homepage "https://github.com/thientran2020/n400"
  version "0.1"

  on_macos do
    url "https://github.com/thientran2020/n400/releases/download/v0.1/n400_0.1_darwin_all.tar.gz"
    sha256 "e7a06eec90e185ca42d7b792e8ad76fb49abcac7e0554a6dbbe822b68254ba78"

    def install
      bin.install "n400"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thientran2020/n400/releases/download/v0.1/n400_0.1_linux_amd64.tar.gz"
      sha256 "ec5cf4c4ebecf0c6b0c9c72dc7d4e9a9cb2d03fc9209b23e9f2e207ff2a98999"

      def install
        bin.install "n400"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thientran2020/n400/releases/download/v0.1/n400_0.1_linux_arm64.tar.gz"
      sha256 "017f63723b0e83ce2105cf48c81908ed6cf757ed3d6c8d762ce0641d96101c50"

      def install
        bin.install "n400"
      end
    end
  end
end
